version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: vaultwarden_server_1
      APP_PORT: 1337
      PROXY_AUTH_ADD: 'false'
    container_name: vaultwarden_app_proxy_1
  server:
    image: vaultwarden/server:latest
    user: '1000:1000'
    restart: always
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ROCKET_PORT: 1337
    container_name: vaultwarden_server_1