version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: dk1337-rustdesk-client_web_1
      APP_PORT: 3000

  web:
    image: ghcr.io/linuxserver/rustdesk:latest
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - NO_DECOR=true
    volumes:
      - ${APP_DATA_DIR}/data/config:/config:rw
    ports:
      - 3045:3001
    restart: always