version: "3.7"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: dk1337-vaultwarden_server
    restart: always
    volumes:
      - ./data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      # ADMIN_TOKEN: "asdiofjqwo498fusdniiJSDIKLFHi8otjhqr4oeu8sfzJLK?P§KOP"

  app_proxy:
    environment:
      APP_HOST: dk1337-vaultwarden_server
      APP_PORT: 80