version: "3.7"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: dk1337-vaultwarden_server
    restart: always
    volumes:
      - ./data:/data
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      # !!! WICHTIG: Setze hier ein starkes, zufälliges Passwort für den Admin-Bereich !!!
      # Generiere eins z.B. mit: openssl rand -base64 48
      ADMIN_TOKEN: "asdiofjqwo498fusdniiJSDIKLFHi8otjhqr4oeu8sfzJLK?P§KOP"
      # DOMAIN: "https://vaultwarden.example.com" # Deine öffentliche Domain (falls vorhanden)

  app_proxy:
    image: ghcr.io/getumbrel/umbrel-app-proxy:v1.0.0
    container_name: dk1337-vaultwarden_proxy
    restart: always
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
    environment:
      APP_HOST: "dk1337-vaultwarden_server"
      APP_PORT: "80"
      PROXY_TARGET_WS_HOST: "dk1337-vaultwarden_server"
      PROXY_TARGET_WS_PORT: "3012"
    depends_on:
      - dk1337-vaultwarden_server