version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: vaultwarden_server_1
      APP_PORT: 8089
      PROXY_AUTH_ADD: "false"

  server:
    image: vaultwarden/server:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      WEBSOCKET_ENABLED: "true"
      ADMIN_TOKEN: ${UMBREL_APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      ROCKET_PORT: 8089
